# Generated by Django 3.1.3 on 2020-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePermutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permutacoes', models.TextField(verbose_name='permutacoes')),
                ('tamanho_permutacao', models.IntegerField(verbose_name='tamanho_permutacao')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('minimo_breakpoints', models.IntegerField(verbose_name='minimo_breakpoints')),
                ('maximo_breakpoints', models.IntegerField(verbose_name='maximo_breakpoints')),
            ],
        ),
    ]
