# Generated by Django 3.1.3 on 2020-11-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_databasepermutation_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabasePermutation',
            new_name='DataSetPermutation',
        ),
    ]
